# Generated by Django 2.1.1 on 2018-09-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter the answer text that you want displayed', verbose_name='Content')),
                ('feedback_initial', models.TextField(blank=True, verbose_name='Initial Feedback')),
                ('feedback_final', models.TextField(verbose_name='Final Feedback')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=False, help_text='How appropriate is this answer', max_length=1)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='JudgmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Judgment Task',
                'verbose_name_plural': 'Judgment Tasks',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, verbose_name='Module Introduction')),
                ('objectives', models.TextField(verbose_name='Learning Objectives')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_information', models.TextField(verbose_name='Initial Cultural Info')),
                ('judgment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_content.JudgmentTask')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('activation', models.TextField(blank=True, verbose_name='Schema Activation')),
                ('new_information', models.TextField(blank=True)),
                ('reflection', models.TextField(blank=True, verbose_name='Reflection Task')),
                ('roleplay', models.TextField(blank=True, verbose_name='Roleplay Task')),
                ('extension', models.TextField(blank=True, verbose_name='Extension Task')),
                ('scenarios', models.ManyToManyField(to='culture_content.Scenario')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(to='culture_content.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_content.JudgmentTask', verbose_name='Judgement Task'),
        ),
    ]
