# Generated by Django 2.1.1 on 2018-09-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating_from',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Rating From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='rating_to',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='Rating From'),
            preserve_default=False,
        ),
    ]
