# Generated by Django 2.0 on 2018-09-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0002_auto_20180925_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='language_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scenario',
            name='name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating_from',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating From'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rating_to',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating To'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='initial_information',
            field=models.TextField(blank=True, verbose_name='Context of the Scenario'),
        ),
    ]
