# Generated by Django 2.0 on 2018-10-02 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0004_auto_20181001_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culture_content.Language'),
            preserve_default=False,
        ),
    ]
