# Generated by Django 2.0 on 2018-10-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0005_module_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='language',
            field=models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic')], max_length=1),
        ),
        migrations.AlterField(
            model_name='topic',
            name='language',
            field=models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic')], max_length=1),
        ),
    ]
