# Generated by Django 2.0 on 2018-10-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0006_auto_20181001_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
