# Generated by Django 2.0 on 2018-10-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0007_delete_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='context_after_feedback',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='language_note_after_feedback',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scenario',
            name='reflection_task',
            field=models.TextField(blank=True, verbose_name='Scenario Reflection Task'),
        ),
        migrations.AddField(
            model_name='topic',
            name='objectives',
            field=models.TextField(blank=True, verbose_name='Learning Objectives'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='language_note',
            field=models.TextField(blank=True, verbose_name='Language Notes'),
        ),
    ]
