# Generated by Django 2.0 on 2018-10-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0008_auto_20181004_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='context_after_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='language_note_after_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
