# Generated by Django 2.0 on 2018-10-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0009_auto_20181004_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjectives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('objectives', models.TextField(verbose_name='Learning Objectives')),
                ('language', models.CharField(choices=[('C', 'Chinese'), ('R', 'Russian'), ('A', 'Arabic')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='objectives',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='culture_content.LearningObjectives'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='objectives',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='culture_content.LearningObjectives'),
        ),
    ]
