# Generated by Django 2.0 on 2018-10-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0010_auto_20181005_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='objectives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culture_content.LearningObjectives'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='objectives',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='culture_content.LearningObjectives'),
        ),
    ]
