# Generated by Django 2.0 on 2018-10-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0011_auto_20181005_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgmenttask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Judgment Task Description'),
        ),
    ]
