# Generated by Django 2.0 on 2018-11-07 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0012_judgmenttask_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
