# Generated by Django 2.0 on 2018-11-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0013_scenario_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
