# Generated by Django 2.0 on 2018-11-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0014_auto_20181107_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating From')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_content.Answer', verbose_name='Options')),
            ],
        ),
    ]
