# Generated by Django 2.0 on 2018-11-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0016_auto_20181127_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
