# Generated by Django 2.0 on 2018-11-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_content', '0017_module_module_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='culture_note',
            field=models.TextField(blank=True, verbose_name='Language Notes'),
        ),
    ]
